### ISSUE TITLE
Drawer Navigation

### ISSUE THREAD

**Issue by dimoreira** [IFours/react-native-twitch#1]
Hi @IFours.

How do you make your menu list buttons navigate to other scenes? I didn't found in your code where the list row press is triggering the navigation (I only found the `closeDrawer` action).

**Comment by ifours** [comment]
Hi,
For now, they trigger only `closeDrawer` action (list items are hardcoded, see `mock_data\menu_data_list.json`)

**Comment by dimoreira** [comment]
Thanks.

I just resolved my issue using _refs_ for the _Drawer_ and _Navigator_ and then passed a _navigate_ method from the base app component to the _Menu_ component at _Drawer_.

Each menu list item can call and navigate to a particular scene.
